# Generated by Django 2.2.7 on 2020-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
