# Generated by Django 2.2.7 on 2020-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='catalogue',
            field=models.TextField(null=True),
        ),
    ]
